[tool.djlint]
ignore = "T002,H006,T003,H031"
extension = "twig"
indent = "4"
profile = "nunjucks"
format_attribute_template_tags = false
max_line_length = "10"
max_attribute_length = "100"
preserve_blank_lines = true